import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Autogenerated sidebar: content added in later tasks appears automatically.
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;