import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Autogenerated sidebar mirrors the docs/ tree (one category per section).
  // The Disrupt section nests WD1/WD2/WDL + cross-game files under its own dirs.
  // Curated ordering / per-game Formats/Guides/Knowledge grouping can be layered
  // on in the progressive MDX phase (T10/T11) once front matter is normalized.
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;