#!/usr/bin/env bash
# Rebuild DuniaDemo_clang_64_dx12_steam_denuvo.pdb from the YAML.
# The YAML is regenerated by build_pdb_yaml.py (combines exports + string symbols).
set -euo pipefail
cd "$(dirname "$0")"

PDB_DIR="../pdb"
mkdir -p "$PDB_DIR"

python3 build_pdb_yaml.py
rm -f "$PDB_DIR/DuniaDemo_clang_64_dx12_steam_denuvo.pdb"
llvm-pdbutil yaml2pdb \
  --pdb="$PDB_DIR/DuniaDemo_clang_64_dx12_steam_denuvo.pdb" \
  DuniaDemo_clang_64_dx12_steam_denuvo.pdb.yaml

echo "OK: $(llvm-pdbutil dump --publics "$PDB_DIR/DuniaDemo_clang_64_dx12_steam_denuvo.pdb" 2>/dev/null | grep -c S_PUB32) public symbols"
